version: '2'
services:
  httpsfrontend:
    image: abiosoft/caddy
    depends_on:
      - pokemap
    links:
      - pokemap
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - /root/.caddy
    environment:
      - EMAIL=youremail@yourdomain.com
    command: 
  pokeworker:
    build: .
    depends_on:
      - pokesql
    links:
      - pokesql
    command: "--auth-service=ptc --username=youruser --password=yourpassword --db-type=mysql --db-host=pokesql --db-name=pogom --db-user=root --db-pass=some-db-password --gmaps-key=someapikey"
    pokemap:
    build: .
    depends_on:
      - pokesql
    links:
      - pokesql
    command: "--no-server --location="Miami, FL" --auth-service=ptc --username=yourotheruser --password=yourotherpassword --db-type=mysql --db-host=pokesql --db-name=pogom --db-user=root --db-pass=some-db-password --gmaps-key=someapikey"
  pokesql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE:pogom
      MYSQL_ROOT_PASSWORD:some-db-password
