version: '2'
services:
  httpsfrontend:
    image: abiosoft/caddy
    links:
      - pokemap
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - /root/.caddy
    environment:
      - EMAIL=youremail@yourdomain.com
    command: "-agree --conf /etc/Caddyfile"
    restart: always
  pokemap:
    build: .
    links:
      - pokesql
    command: "--location=\"Orlando, FL\" --auth-service=ptc --username=youruser --password=yourpassword --db-type=mysql --db-host=pokesql --db-name=pogom --db-user=pogom --db-pass=somedbpassword --gmaps-key=someapikey"
    restart: always
  pokeworker:
    build: .
    links:
      - pokesql
    command: "--location=\"Miami, FL\" --auth-service=ptc --username=yourotheruser --password=yourotherpassword --db-type=mysql --db-host=pokesql --db-name=pogom --db-user=pogom --db-pass=somedbpassword --no-server --gmaps-key=someapikey"
    restart: always
  pokesql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=pogom
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=pogom
      - MYSQL_PASSWORD=somedbpassword
    restart: always
